server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-manager
    username: postgres
    password: postgres
    hikari:
      schema: task_schema
      connection-init-sql: create schema if not exists task_schema
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    jwt:
      secret: special-secret-key
      expiration: 3600000

